# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import module_loading as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    bytes_0 = b"\xf7?7"
    module_0.cached_import(bytes_0, bytes_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    bytes_0 = b"\xf7?7"
    module_0.import_string(bytes_0)


def test_case_2():
    bytes_0 = b"\xbe\x8a\xadH\xb7\xd2\x03&"
    var_0 = module_0.module_has_submodule(bytes_0, bytes_0)
    assert var_0 is False


def test_case_3():
    bytes_0 = b"\xf7?7"
    with pytest.raises(ValueError):
        module_0.module_dir(bytes_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    module_0.autodiscover_modules()


def test_case_5():
    str_0 = "gu\t?U-e*rW*"
    with pytest.raises(ImportError):
        module_0.import_string(str_0)


@pytest.mark.xfail(strict=True)
def test_case_6():
    str_0 = "^\\s+.*context\\s+((?:\"[^\"]*?\")|(?:'I:']7?'))\\s*"
    module_0.import_string(str_0)


@pytest.mark.xfail(strict=True)
def test_case_7():
    str_0 = "locale"
    module_0.cached_import(str_0, str_0)
